# page-view settings
page-view:
  credential: <XXX.json>  # service account credential file
  property_id: <XXXXXXX>  #XXXXXXXX
  start:                  # Beginning of report
    - 30daysAgo
    - 3653daysAgo
    - 365daysAgo
    - 7daysAgo
    - 1daysAgo
  end: today              # End of report
  n_posts: 5              # Number of popular posts
  show_views: true        # If n_views is shown or not
popular_post_title: Popular Posts (Last Month) # Title of sidebar section
adsense_popular: xxx        # Google Adsense infeed ad, if you want
